server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/data?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: mac
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 1MB
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com/gzb/postsupervisionrobots/entity
  configuration:
    #??????
    map-underscore-to-camel-case: true
